In [2]:
import pandas as pd
from teradataml import (
    create_context,
    get_context,
    remove_context,
    copy_to_sql
)
import getpass
from teradatasqlalchemy.types import *

## DB Connect

In [3]:
host = input("Host:")
username = input("Username:")
password = getpass.getpass("Password:")
database = input("Database (defaults to user):")
#eng=create_context(host = host, username=username, password = password, logmech="TDNEGO", database=database)
#conn=eng.connect()

Host: vantage24.td.teradata.com
Username: MS255220
Password: ········
Database (defaults to user): MS255220

# Data Preparation

## ADS Extraction

### Baseline

In [6]:
pd.read_sql('''Select * from AnalyticalDataset_Base;''',conn)

,ID,Minimum,Skewness,StandardDeviation,Maximum,Kurtosis,Mean,ACF_0,ACF_1,ACF_2,...,ACF_8,ACF_9,ACF_10,ACF_11,ACF_12,ACF_13,ACF_14,ACF_15,label,sample_id
0,13948,-0.043640,-0.040900,0.010355,0.042236,0.962909,-0.000034,1.0,0.049531,-0.720331,...,0.472041,0.050945,-0.358238,-0.012693,0.322554,-0.018490,-0.313451,-0.010188,1,3
1,265,-0.036865,-0.022974,0.007521,0.035187,0.841989,-0.000032,1.0,0.036923,-0.516263,...,0.092785,-0.075251,-0.019032,0.097485,-0.000274,-0.060367,0.015430,0.037834,0,2
2,11399,-0.114410,-0.219908,0.013477,0.095398,14.207327,-0.000033,1.0,-0.417652,-0.095391,...,0.437300,-0.305323,0.155128,0.078530,-0.273265,0.172337,-0.119359,0.045247,1,4
3,5159,-0.589081,0.102121,0.042995,0.567871,42.281495,-0.000021,1.0,-0.386985,-0.178911,...,0.143291,-0.059380,-0.187700,0.068053,-0.155512,-0.111544,-0.038500,-0.121811,0,1
4,6974,-0.234558,-0.093080,0.035052,0.195343,3.253981,-0.000025,1.0,-0.189513,-0.447794,...,0.116018,-0.164453,-0.189172,0.072240,-0.028602,-0.148333,-0.064982,0.009170,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15522,959,-0.411285,0.928649,0.082551,0.539093,9.408610,-0.000086,1.0,0.060851,-0.227427,...,0.220345,0.363266,-0.042834,-0.068449,-0.123257,-0.110981,-0.177275,-0.031301,0,1
15523,10543,-0.061096,0.473167,0.009367,0.086060,9.091567,-0.000037,1.0,-0.238906,-0.113764,...,0.327921,-0.131038,0.117863,0.137671,-0.129321,0.070898,-0.040474,-0.063511,1,4
15524,9666,-0.066589,0.058031,0.010741,0.069183,4.029779,-0.000035,1.0,-0.277736,-0.182393,...,0.281136,-0.270844,0.179100,0.043053,-0.124568,0.192353,-0.171756,0.060097,1,3
15525,5037,-0.120239,0.135540,0.014595,0.140686,7.919405,-0.000039,1.0,-0.070503,-0.617591,...,-0.092941,0.011944,0.086747,-0.127893,-0.037727,0.173158,0.070780,-0.077464,0,1
15526,7382,-1.000000,0.157276,0.245769,0.999969,3.335558,-0.000317,1.0,0.100142,-0.477301,...,-0.042105,0.016953,0.020411,-0.037020,0.022857,0.017733,-0.024229,0.022487,0,1

In [23]:
Base = pd.read_sql('''SELECT * from AnalyticalDataset_Base;''',conn)
Base.head()

,ID,Minimum,Skewness,StandardDeviation,Maximum,Kurtosis,Mean,ACF_0,ACF_1,ACF_2,...,ACF_8,ACF_9,ACF_10,ACF_11,ACF_12,ACF_13,ACF_14,ACF_15,label,sample_id
0,13948,-0.043640,-0.040900,0.010355,0.042236,0.962909,-0.000034,1.0,0.049531,-0.720331,...,0.472041,0.050945,-0.358238,-0.012693,0.322554,-0.018490,-0.313451,-0.010188,1,4
1,265,-0.036865,-0.022974,0.007521,0.035187,0.841989,-0.000032,1.0,0.036923,-0.516263,...,0.092785,-0.075251,-0.019032,0.097485,-0.000274,-0.060367,0.015430,0.037834,0,1
2,11399,-0.114410,-0.219908,0.013477,0.095398,14.207327,-0.000033,1.0,-0.417652,-0.095391,...,0.437300,-0.305323,0.155128,0.078530,-0.273265,0.172337,-0.119359,0.045247,1,4
3,5159,-0.589081,0.102121,0.042995,0.567871,42.281495,-0.000021,1.0,-0.386985,-0.178911,...,0.143291,-0.059380,-0.187700,0.068053,-0.155512,-0.111544,-0.038500,-0.121811,0,1
4,6974,-0.234558,-0.093080,0.035052,0.195343,3.253981,-0.000025,1.0,-0.189513,-0.447794,...,0.116018,-0.164453,-0.189172,0.072240,-0.028602,-0.148333,-0.064982,0.009170,0,2

In [223]:
Base.rename(columns={'Minimum': 'Minimum_t', 'Skewness': 'Skewness_t', 'StandardDeviation':'StandardDeviation_t','Maximum':'Maximum_t','Kurtosis':'Kurtosis_t','Mean':'Mean_t'}, inplace=True)
Base

,ID,Minimum_t,Skewness_t,StandardDeviation_t,Maximum_t,Kurtosis_t,Mean_t,ACF_0,ACF_1,ACF_2,...,ACF_8,ACF_9,ACF_10,ACF_11,ACF_12,ACF_13,ACF_14,ACF_15,label,sample_id
0,13948,-0.043640,-0.040900,0.010355,0.042236,0.962909,-0.000034,1.0,0.049531,-0.720331,...,0.472041,0.050945,-0.358238,-0.012693,0.322554,-0.018490,-0.313451,-0.010188,1,4
1,265,-0.036865,-0.022974,0.007521,0.035187,0.841989,-0.000032,1.0,0.036923,-0.516263,...,0.092785,-0.075251,-0.019032,0.097485,-0.000274,-0.060367,0.015430,0.037834,0,1
2,11399,-0.114410,-0.219908,0.013477,0.095398,14.207327,-0.000033,1.0,-0.417652,-0.095391,...,0.437300,-0.305323,0.155128,0.078530,-0.273265,0.172337,-0.119359,0.045247,1,4
3,5159,-0.589081,0.102121,0.042995,0.567871,42.281495,-0.000021,1.0,-0.386985,-0.178911,...,0.143291,-0.059380,-0.187700,0.068053,-0.155512,-0.111544,-0.038500,-0.121811,0,1
4,6974,-0.234558,-0.093080,0.035052,0.195343,3.253981,-0.000025,1.0,-0.189513,-0.447794,...,0.116018,-0.164453,-0.189172,0.072240,-0.028602,-0.148333,-0.064982,0.009170,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15522,959,-0.411285,0.928649,0.082551,0.539093,9.408610,-0.000086,1.0,0.060851,-0.227427,...,0.220345,0.363266,-0.042834,-0.068449,-0.123257,-0.110981,-0.177275,-0.031301,0,1
15523,10543,-0.061096,0.473167,0.009367,0.086060,9.091567,-0.000037,1.0,-0.238906,-0.113764,...,0.327921,-0.131038,0.117863,0.137671,-0.129321,0.070898,-0.040474,-0.063511,1,3
15524,9666,-0.066589,0.058031,0.010741,0.069183,4.029779,-0.000035,1.0,-0.277736,-0.182393,...,0.281136,-0.270844,0.179100,0.043053,-0.124568,0.192353,-0.171756,0.060097,1,4
15525,5037,-0.120239,0.135540,0.014595,0.140686,7.919405,-0.000039,1.0,-0.070503,-0.617591,...,-0.092941,0.011944,0.086747,-0.127893,-0.037727,0.173158,0.070780,-0.077464,0,1
15526,7382,-1.000000,0.157276,0.245769,0.999969,3.335558,-0.000317,1.0,0.100142,-0.477301,...,-0.042105,0.016953,0.020411,-0.037020,0.022857,0.017733,-0.024229,0.022487,0,1

In [224]:
Base_Features = Base.drop(["ID",'ACF_0','label','sample_id'],axis = 1)
scaler = StandardScaler()
Base_Features = pd.DataFrame(scaler.fit_transform(Base_Features),columns = Base_Features.columns)
Base_Features = pd.concat([Base_Features,Base[["ID"]]],axis = 1)
Base_Features.head()

,Minimum_t,Skewness_t,StandardDeviation_t,Maximum_t,Kurtosis_t,Mean_t,ACF_1,ACF_2,ACF_3,ACF_4,...,ACF_7,ACF_8,ACF_9,ACF_10,ACF_11,ACF_12,ACF_13,ACF_14,ACF_15,ID
0,0.461523,-0.088045,-0.282147,-0.467880,-0.299882,-0.033439,0.117703,-1.660902,-0.548801,2.217293,...,0.245799,1.999473,0.522186,-1.942063,-0.166657,2.104988,-0.171554,-1.851997,0.132815,13948
1,0.489402,-0.059535,-0.340764,-0.496968,-0.303086,-0.011017,0.074434,-0.807880,-0.537917,0.446489,...,0.480288,0.210095,-0.177939,-0.130889,0.500797,0.317068,-0.379966,0.204995,0.420171,265
2,0.170304,-0.372744,-0.217565,-0.248519,0.051004,-0.023254,-1.485572,0.951406,0.856388,-2.022257,...,-0.598719,1.835560,-1.454354,0.799027,0.385966,-1.194841,0.778156,-0.638043,0.464530,11399
3,-1.782967,0.139419,0.392931,1.701041,0.794777,0.089808,-1.380330,0.602281,2.064854,-1.127211,...,-1.294110,0.448390,-0.089887,-1.031485,0.322499,-0.542688,-0.634668,-0.132312,-0.535112,5159
4,-0.324105,-0.171033,0.228654,0.163883,-0.239184,0.052878,-0.702648,-0.521672,1.353606,0.960319,...,0.290135,0.319712,-0.672826,-1.039342,0.347867,0.160180,-0.817758,-0.297944,0.248653,6974

In [26]:
Base_Labels = Base[['ID','label','sample_id']]
Base_Labels.head()

      ID  label  sample_id
0  13948      1          4
1    265      0          1
2  11399      1          4
3   5159      0          1
4   6974      0          2

### CWT

In [27]:
pd.read_sql('''Select top 5 * from AnalyticalDataset;''',conn)

,Minimum_0,Maximum_0,Skewness_0,StandardDeviation_0,Kurtosis_0,Mean_0,Minimum_1,Maximum_1,Skewness_1,StandardDeviation_1,...,Mean_19,Minimum_20,Maximum_20,Skewness_20,StandardDeviation_20,Kurtosis_20,Mean_20,ID,label,sample_id
0,5.766424e-32,0.000330,2.974505,0.000035,12.416755,0.000024,1.794711e-32,0.001255,3.892682,0.000105,...,0.000006,6.251575e-37,0.000003,4.319419,2.573537e-07,26.127526,1.294949e-07,13948,1,3
1,6.963262e-30,0.036648,6.490304,0.001913,66.441477,0.000805,2.151474e-30,0.058992,6.480847,0.003730,...,0.000544,1.505276e-37,0.007809,3.572269,8.452644e-04,17.941031,4.918190e-04,6974,0,1
2,6.145488e-30,0.360402,17.167510,0.014519,346.105387,0.002054,1.905652e-30,0.623495,18.008267,0.022262,...,0.001394,1.023474e-34,0.014320,3.481643,1.616163e-03,16.639438,9.748059e-04,5159,0,1
3,2.803186e-29,0.910930,8.611525,0.055993,91.182791,0.014402,8.665642e-30,1.302791,9.232026,0.084883,...,0.006706,4.416488e-36,0.066664,3.132745,8.824446e-03,11.719471,4.969789e-03,2814,0,2
4,1.872759e-30,0.257037,7.739893,0.014572,85.593338,0.004133,5.788096e-31,0.398699,8.214793,0.019467,...,0.000490,4.024510e-35,0.005200,3.442117,7.117157e-04,13.878279,3.785536e-04,7239,0,1

In [28]:
CWT = pd.read_sql('''SELECT * from AnalyticalDataset;''',conn)
CWT.head()

,Minimum_0,Maximum_0,Skewness_0,StandardDeviation_0,Kurtosis_0,Mean_0,Minimum_1,Maximum_1,Skewness_1,StandardDeviation_1,...,Mean_19,Minimum_20,Maximum_20,Skewness_20,StandardDeviation_20,Kurtosis_20,Mean_20,ID,label,sample_id
0,5.766424e-32,0.000330,2.974505,0.000035,12.416755,0.000024,1.794711e-32,0.001255,3.892682,0.000105,...,0.000006,6.251575e-37,0.000003,4.319419,2.573537e-07,26.127526,1.294949e-07,13948,1,3
1,1.021549e-32,0.000481,4.351059,0.000036,31.771739,0.000022,3.052534e-33,0.001731,7.610484,0.000084,...,0.000004,9.803884e-37,0.000016,3.591450,1.801768e-06,15.455125,8.236616e-07,265,0,1
2,3.119288e-32,0.017545,8.723121,0.001017,95.747449,0.000216,9.552105e-33,0.017676,8.472368,0.001123,...,0.000007,4.317263e-36,0.000023,3.989969,2.430950e-06,20.494126,1.156481e-06,11399,1,3
3,6.145488e-30,0.360402,17.167510,0.014519,346.105387,0.002054,1.905652e-30,0.623495,18.008267,0.022262,...,0.001394,1.023474e-34,0.014320,3.481643,1.616163e-03,16.639438,9.748059e-04,5159,0,1
4,6.963262e-30,0.036648,6.490304,0.001913,66.441477,0.000805,2.151474e-30,0.058992,6.480847,0.003730,...,0.000544,1.505276e-37,0.007809,3.572269,8.452644e-04,17.941031,4.918190e-04,6974,0,1

In [110]:
CWT_Features = CWT.drop(['ID','label','sample_id'],axis = 1)
scaler = StandardScaler()
CWT_Features = pd.DataFrame(scaler.fit_transform(CWT_Features),columns = CWT_Features.columns)
CWT_Features = pd.concat([CWT_Features,CWT[["ID"]]],axis = 1)
CWT_Features.head()

,Minimum_0,Maximum_0,Skewness_0,StandardDeviation_0,Kurtosis_0,Mean_0,Minimum_1,Maximum_1,Skewness_1,StandardDeviation_1,...,StandardDeviation_19,Kurtosis_19,Mean_19,Minimum_20,Maximum_20,Skewness_20,StandardDeviation_20,Kurtosis_20,Mean_20,ID
0,-0.081652,-0.344018,-0.805744,-0.296480,-0.614325,-0.235871,-0.081272,-0.349841,-0.678955,-0.291402,...,-0.185213,-0.022902,-0.177259,-0.058256,-0.198191,-0.132023,-0.187484,-0.190497,-0.184959,13948
1,-0.081879,-0.343244,-0.617085,-0.296398,-0.540318,-0.236169,-0.081502,-0.348266,-0.175202,-0.292400,...,-0.186152,0.716649,-0.177611,-0.058228,-0.197934,-0.473681,-0.187253,-0.535176,-0.184772,265
2,-0.081778,-0.255393,-0.017885,-0.223089,-0.295695,-0.202224,-0.081402,-0.295557,-0.058419,-0.244761,...,-0.184842,0.932322,-0.177059,-0.057964,-0.197794,-0.286644,-0.187159,-0.372435,-0.184683,11399
3,-0.052571,1.509730,1.139436,0.785776,0.661593,0.120099,-0.052107,1.707119,1.233673,0.724172,...,0.007666,-0.494149,0.048488,-0.050198,0.076204,-0.525217,0.054559,-0.496927,0.077549,5159
4,-0.048665,-0.157045,-0.323897,-0.156191,-0.407752,-0.098807,-0.048309,-0.158978,-0.328265,-0.125254,...,-0.112157,-0.488367,-0.089793,-0.058294,-0.048590,-0.482683,-0.060912,-0.454891,-0.052533,6974

In [30]:
CWT_Labels = CWT[['ID','label','sample_id']]
CWT_Labels.head()

      ID  label  sample_id
0  13948      1          3
1    265      0          1
2  11399      1          3
3   5159      0          1
4   6974      0          1

## ADS Loading

In [97]:
eng=create_context(host = host, username=username, password = password, logmech="TDNEGO", database=username)
conn=eng.connect()

/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/context/context.py:462: UserWarning: [Teradata][teradataml](TDML_2002) Overwriting an existing context associated with Teradata Vantage Connection. Most of the operations on any teradataml DataFrames created before this will not work.
  warnings.warn(Messages.get_message(MessageCodes.OVERWRITE_CONTEXT))
Exception closing connection TeradataConnection uConnHandle=4
Traceback (most recent call last):
  File "/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 379, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 701, in do_close
    dbapi_connection.close()
  File "/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradatasql/__init__.py", line 208, in close
    raise OperationalError(sErr)
teradatasql.OperationalError: [Version 17.20.0.32] [Session 33106] [Teradata SQL Driver] Failure sending Logoff Request message
 at gosqldriver/teradatasql.formatError ErrorUtil.go:89
 at gosqldriver/teradatasql.(*teradataConnection).makeDriverError ErrorUtil.go:180
 at gosqldriver/teradatasql.(*teradataConnection).socketSendMessage NetworkIO.go:325
 at gosqldriver/teradatasql.(*teradataConnection).socketSendAndReceiveContext NetworkIO.go:73
 at gosqldriver/teradatasql.(*teradataConnection).sendAndReceive NetworkIO.go:29
 at gosqldriver/teradatasql.(*teradataConnection).Close TeradataConnection.go:1138
 at database/sql.(*driverConn).finalClose.func2 sql.go:645
 at database/sql.withLock sql.go:3439
 at database/sql.(*driverConn).finalClose sql.go:643
 at database/sql.(*DB).Close sql.go:903
 at main.goCloseConnection goside.go:450
 at _cgoexp_50e73dec876f_goCloseConnection _cgo_gotypes.go:294
 at runtime.cgocallbackg1 cgocall.go:316
 at runtime.cgocallbackg cgocall.go:235
 at runtime.cgocallback asm_amd64.s:994
 at runtime.goexit asm_amd64.s:1594
Caused by write tcp 172.20.61.143:57024->141.206.0.153:1025: write: broken pipe

In [112]:
copy_to_sql(df=Base_Features, 
            table_name="Sonar_Base_Features",     
            schema_name=username,
            primary_index="ID", 
            if_exists="replace"
)
copy_to_sql(df=Base_Labels, 
            table_name="Sonar_Base_Labels",     
            schema_name=username,
            primary_index="ID", 
            if_exists="replace",
            types = {"label":INTEGER})

/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))

In [113]:
copy_to_sql(df=CWT_Features, 
            table_name="Sonar_CWT_Features",     
            schema_name=username,
            primary_index="ID", 
            if_exists="replace"
)
copy_to_sql(df=CWT_Labels, 
            table_name="Sonar_CWT_Labels",     
            schema_name=username,
            primary_index="ID", 
            if_exists="replace",
            types = {"label":INTEGER})

/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))

# ModelOps Scripting

In [39]:
configure.val_install_location = "TRNG_XSP"
configure.byom_install_location = "TRNG_BYOM"

### Scoring Table

In [119]:
pd.read_sql('''CREATE MULTISET TABLE Sonar_CWT_Predictions
    (
        job_id VARCHAR(255),
        ID BIGINT,
        label BIGINT,
        json_report CLOB(1048544000) CHARACTER SET UNICODE
    )
    PRIMARY INDEX ( job_id );''',conn)

Empty DataFrame
Columns: []
Index: []

### BYOM Table

In [298]:
pd.read_sql('''Select * from tmo_byom_models;''',conn)

,model_version,model_id,model_type,project_id,deployed_at,model
0,45dad295-8b46-41fa-bc88-be089a8f0de7,935fb7ac-4341-4b87-88aa-9087a3e3b044,PMML,25243346-a4b2-4b36-912c-467761e28e41,2023-12-20 02:24:30.910,"b'<?xml version=""1.0"" encoding=""UTF-8""?>\n<PMM..."

## Baseline

### Training

The training function takes the following shape

```python
def train(context: ModelContext, **kwargs):
    aoa_create_context()
    
    # your training code
    
    # save your model
    joblib.dump(model, f"{context.artifact_output_path}/model.joblib")
    
    record_training_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [48]:
from aoa import (
    record_training_stats,
    save_plot,
    aoa_create_context,
    ModelContext
)
from teradataml import DataFrame
import joblib

def train(context: ModelContext, **kwargs):
    aoa_create_context()
    
    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]
    feature_names_str = ",".join(["'{}'".format(value) for value in feature_names])
    #feature_names_str = ",".join(['''"{}"'''.format(value) for value in feature_names])

    # read training dataset from Teradata and convert to pandas
    train_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Starting training...")

    # fit model to training data
    model_query = f'''
    CREATE TABLE Sonar_DF_Base AS (
        SELECT * FROM TD_DecisionForest(
            ON ({context.dataset_info.sql}) as InputTable
        USING
            ResponseColumn('label')
            InputColumns({feature_names_str})
            ModelType('CLASSIFICATION')
            MaxDepth({context.hyperparams["MaxDepth"]})
            NumTrees({context.hyperparams["NumTrees"]})
            MinNodeSize({context.hyperparams["MinNodeSize"]})
            Mtry({context.hyperparams["Mtry"]})
        ) AS dt
    ) WITH DATA;'''

    try:
        pd.read_sql(model_query,get_context())
    except:
        pd.read_sql(f'DROP TABLE Sonar_DF_Base;',get_context())
        pd.read_sql(model_query,get_context())

    print("Finished training")
    # export model artefacts
    
    print("Saved trained model")

    record_training_stats(train_df,
                          features=feature_names,
                          targets=[target_name],
                          categorical=[target_name],
                          context=context)

In [51]:
from aoa import ModelContext, DatasetInfo
from teradataml import configure

# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the training dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_Base_Features F 
JOIN (Select ID, label from Sonar_Base_Labels where sample_id in (1,3)) L
ON F.ID = L.ID
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_Base_Statistics_Metadata"
}
hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_t', 'Skewness_t', 'StandardDeviation_t', 'Maximum_t', 'Kurtosis_t',
       'Mean_t', 'ACF_1', 'ACF_2', 'ACF_3', 'ACF_4', 'ACF_5', 'ACF_6', 'ACF_7',
       'ACF_8', 'ACF_9', 'ACF_10', 'ACF_11', 'ACF_12', 'ACF_13', 'ACF_14',
       'ACF_15']
 
dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata)


ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1")

train(context=ctx)

Starting training...
Finished training
Saved trained model

### Evaluation

The evaluation function takes the following shape

```python
def evaluate(context: ModelContext, **kwargs):
    aoa_create_context()

    # read your model
    model = joblib.load(f"{context.artifact_input_path}/model.joblib")
    
    # your evaluation logic
    
    record_evaluation_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [52]:
from sklearn import metrics
from teradataml import *
from aoa import (
    record_evaluation_stats,
    save_plot,
    aoa_create_context,
    ModelContext
)

import joblib
import json
import pandas as pd

def evaluate(context: ModelContext, **kwargs):
    aoa_create_context()
    configure.val_install_location = os.environ.get("AOA_VAL_INSTALL_DB", "TRNG_XSP") 
     
    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]

    test_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Evaluating")

    query = f'''
        SELECT * FROM TD_DecisionForestPredict (
            ON ({context.dataset_info.sql}) AS InputTable
            ON Sonar_DF_Base AS ModelTable DIMENSION
        USING
            IdColumn ('{context.dataset_info.entity_key}')
            Responses('0','1')
            Accumulate('{context.dataset_info.target_names[0]}')
            OutputProb('true')
        ) AS dt;'''
    
    predictions_df = DataFrame.from_query(query)
    
    print("Finished Evaluating")

    statistics = valib.Frequency(data=predictions_df, columns=target_name)
    eval_stats = ClassificationEvaluator(data=predictions_df, observation_column=target_name, prediction_column='prediction', num_labels=int(statistics.result.count(True).to_pandas().count_xval))
    eval_data = eval_stats.output_data.to_pandas().reset_index(drop=True)

    evaluation = {
        'Accuracy': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Accuracy')].MetricValue.item()),
        'Recall': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Recall')].MetricValue.item()),
        'Precision': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Precision')].MetricValue.item()),
        'f1-score': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-F1')].MetricValue.item())
    }

    with open(f"{context.artifact_output_path}/metrics.json", "w+") as f:
        json.dump(evaluation, f)
        
    # Confusion Matrix sklearn metrics
    predictions_pdf = predictions_df.to_pandas()
    cm = metrics.confusion_matrix(predictions_pdf[target_name],predictions_pdf["prediction"])
    cmd = metrics.ConfusionMatrixDisplay(cm,display_labels = ['notWhale','Whale'])
    cmd.plot()
    save_plot('Confusion Matrix', context=context)
    
    fpr, tpr, thresholds = metrics.roc_curve(predictions_pdf[target_name],predictions_pdf["prediction"] , pos_label=1)
    roc_AUC = metrics.auc(fpr,tpr)
    rcd = metrics.RocCurveDisplay(fpr = fpr, tpr = tpr,roc_auc = roc_AUC, estimator_name = 'TD_DecisionForest')
    
    rcd.plot()
    save_plot('ROC Curve', context=context)
    
    record_evaluation_stats(features_df=test_df,
                            predicted_df=predictions_df,
                            context=context)

In [53]:
# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the evaluation dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_Base_Features F 
JOIN (Select ID, label from Sonar_Base_Labels where sample_id in (2,4)) L
ON F.ID = L.ID
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_Base_Statistics_Metadata"
}
hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_t', 'Skewness_t', 'StandardDeviation_t', 'Maximum_t', 'Kurtosis_t',
       'Mean_t', 'ACF_1', 'ACF_2', 'ACF_3', 'ACF_4', 'ACF_5', 'ACF_6', 'ACF_7',
       'ACF_8', 'ACF_9', 'ACF_10', 'ACF_11', 'ACF_12', 'ACF_13', 'ACF_14',
       'ACF_15']


dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata)

ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   artifact_input_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1")

evaluate(context=ctx)

# view evaluation results
with open(f"{ctx.artifact_output_path}/metrics.json") as f:
    print(json.load(f))

Evaluating
Finished Evaluating

/var/folders/s4/bz6clqz1235_rx2pr6_pm44c0000gq/T/ipykernel_45097/4029010061.py:41: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eval_stats = ClassificationEvaluator(data=predictions_df, observation_column=target_name, prediction_column='prediction', num_labels=int(statistics.result.count(True).to_pandas().count_xval))

{'Accuracy': '0.77', 'Recall': '0.76', 'Precision': '0.77', 'f1-score': '0.76'}

### Scoring

The scoring function takes the following shape

```python
def score(context: ModelContext, **kwargs):
    aoa_create_context()

    # read your model
    model = joblib.load(f"{context.artifact_input_path}/model.joblib")
    
    # your evaluation logic
    
    record_scoring_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [54]:
# %%writefile ../model_modules/scoring.py

from teradataml import copy_to_sql, DataFrame
from aoa import (
    record_scoring_stats,
    aoa_create_context,
    ModelContext
)

import joblib
import pandas as pd
import json

def JSON(x):
    Dict = {"prob_0":x["prob_0"],"prob_1":x["prob_1"],"prediction":x["prediction"]}
    return json.dumps(Dict)

def score(context: ModelContext, **kwargs):

    aoa_create_context()

    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]
    entity_key = context.dataset_info.entity_key

    features_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Scoring")
    
    predictions_df = DataFrame.from_query(
        f'''SELECT * FROM TD_DecisionForestPredict (
            ON ({context.dataset_info.sql}) AS InputTable
            ON Sonar_DF_Base AS ModelTable DIMENSION
        USING
            IdColumn ('{context.dataset_info.entity_key}')
            Responses('0','1')
            OutputProb('true')
        ) AS dt;''')
    
    print("Finished Scoring")

    # store the predictions
    predictions_pdf = predictions_df.to_pandas(all_rows = True)
    # add job_id column so we know which execution this is from if appended to predictions table
    predictions_pdf["job_id"] = context.job_id
    predictions_pdf["json_report"] = predictions_pdf.apply(JSON,axis = 1)
    predictions_pdf.rename(columns={"prediction": target_name}, inplace=True) 
    predictions_pdf = predictions_pdf[["job_id", entity_key, target_name, "json_report"]]

    copy_to_sql(df=predictions_pdf,
                schema_name=context.dataset_info.predictions_database,
                table_name=context.dataset_info.predictions_table,
                index=False,
                if_exists="append")
    
    print("Saved predictions in Teradata")

    # calculate stats of this job
    predictions_df = DataFrame.from_query(f"""
        SELECT 
            * 
        FROM {context.dataset_info.get_predictions_metadata_fqtn()} 
            WHERE job_id = '{context.job_id}'
    """)

    record_scoring_stats(features_df=features_df, predicted_df=predictions_df, context=context)

In [55]:
from aoa import ModelContext, DatasetInfo
from teradataml import configure
# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the scoring dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_Base_Features F 
JOIN (Select ID, label from Sonar_Base_Labels) L
ON F.ID = L.ID
where F.ID MOD 5 = 0
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_Base_Statistics_Metadata"
}

predictions = {
    "database": username,
    "table": "Sonar_Base_Predictions"
}

hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_t', 'Skewness_t', 'StandardDeviation_t', 'Maximum_t', 'Kurtosis_t',
       'Mean_t', 'ACF_1', 'ACF_2', 'ACF_3', 'ACF_4', 'ACF_5', 'ACF_6', 'ACF_7',
       'ACF_8', 'ACF_9', 'ACF_10', 'ACF_11', 'ACF_12', 'ACF_13', 'ACF_14',
       'ACF_15']


import uuid
job_id=str(uuid.uuid4())

dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata,
                           predictions=predictions)

ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   artifact_input_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1",
                   job_id=job_id)

score(context=ctx)

Scoring
Finished Scoring

/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))

Saved predictions in Teradata

### BYOM

In [68]:
from nyoka import skl_to_pmml
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [65]:
DF = pd.read_sql("""
SELECT 
    F.*, L.label
FROM Sonar_Base_Features F 
JOIN (Select ID, label from Sonar_Base_Labels where sample_id in (1,3)) L
ON F.ID = L.ID
""",conn)
DF.head()

,Minimum_t,Skewness_t,StandardDeviation_t,Maximum_t,Kurtosis_t,Mean_t,ACF_1,ACF_2,ACF_3,ACF_4,...,ACF_8,ACF_9,ACF_10,ACF_11,ACF_12,ACF_13,ACF_14,ACF_15,ID,label
0,0.574797,-0.022720,-0.386006,-0.570760,-0.334013,-0.041279,-0.453876,-0.952916,0.768711,0.448319,...,-1.794783,0.051050,1.776919,-1.419430,-0.755355,1.881045,0.096322,-1.644598,14213,1
1,0.489402,-0.059535,-0.340764,-0.496968,-0.303086,-0.011017,0.074434,-0.807880,-0.537917,0.446489,...,0.210095,-0.177939,-0.130889,0.500797,0.317068,-0.379966,0.204995,0.420171,265,0
2,0.200066,1.657925,-0.295585,0.045640,0.872487,-0.030288,-1.235249,-0.722547,1.615646,-0.258373,...,-0.447254,0.469011,-0.125898,0.089340,0.169947,-0.167836,0.228408,0.295690,6301,0
3,-1.782967,0.139419,0.392931,1.701041,0.794777,0.089808,-1.380330,0.602281,2.064854,-1.127211,...,0.448390,-0.089887,-1.031485,0.322499,-0.542688,-0.634668,-0.132312,-0.535112,5159,0
4,0.594261,-0.067773,-0.433196,-0.590026,-0.321811,-0.032193,-0.086685,-0.635770,-0.161989,0.332648,...,0.198190,0.551131,-0.023175,0.363088,0.427026,-0.107551,0.139237,-0.008335,9319,1

In [69]:
entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_t', 'Skewness_t', 'StandardDeviation_t', 'Maximum_t', 'Kurtosis_t',
       'Mean_t', 'ACF_1', 'ACF_2', 'ACF_3', 'ACF_4', 'ACF_5', 'ACF_6', 'ACF_7',
       'ACF_8', 'ACF_9', 'ACF_10', 'ACF_11', 'ACF_12', 'ACF_13', 'ACF_14',
       'ACF_15']

pipeline = Pipeline([
	("classifier", RandomForestClassifier(n_estimators = 30, max_depth=8, criterion = 'gini',random_state = 0))
])
pipeline.fit(DF.drop(["ID","label"],axis = 1),DF["label"])
skl_to_pmml(pipeline, feature_names, "label", "model.pmml")

In [71]:
save_byom(model_id="sonar_rf_base", model_file="model.pmml", table_name="tmo_byom_models")

Model is saved.

In [72]:
query = f"""
SELECT * FROM TRNG_BYOM.PMMLPredict (
    ON (SELECT * FROM Sonar_Base_Features WHERE ID MOD 5 = 0) AS DataTable
    ON (SELECT * FROM tmo_byom_models 
            WHERE model_id='sonar_rf_base') AS ModelTable DIMENSION
    USING
      Accumulate ('ID')
) AS td;
"""

pd.read_sql(query, conn)

         ID prediction                                        json_report
0      8585          1  {"probability_0":0.250870673703186,"probabilit...
1      6280          0  {"probability_0":0.9790584546174469,"probabili...
2     15395          1  {"probability_0":0.20975992534649993,"probabil...
3      7565          0  {"probability_0":0.769659086054454,"probabilit...
4     11235          0  {"probability_0":0.6535155351380876,"probabili...
...     ...        ...                                                ...
3100   5140          0  {"probability_0":0.9542082021586734,"probabili...
3101  14785          1  {"probability_0":0.16804512638660477,"probabil...
3102  11155          0  {"probability_0":0.5219669126866233,"probabili...
3103  12745          1  {"probability_0":0.166924219492137,"probabilit...
3104  10665          1  {"probability_0":0.4392075906159906,"probabili...

[3105 rows x 3 columns]

In [76]:
delete_byom(model_id="sonar_rf_base", table_name="tmo_byom_models")

Model is deleted.

### Custom Evaluation Script for BYOM Scoring

In [ ]:
import json
import os
import uuid
from aoa import (
    record_evaluation_stats,
    aoa_create_context,
    store_byom_tmp,
    save_plot,
    ModelContext,
    DatasetInfo
)
from sklearn import metrics
from teradataml import *

byom_temp_table = f"byom_{str(uuid.uuid4()).replace('-','')}"

def evaluate(context: ModelContext, **kwargs):
    aoa_create_context()

    configure.val_install_location = os.environ.get("AOA_VAL_INSTALL_DB", "TRNG_XSP") 
    configure.byom_install_location = os.environ.get("AOA_BYOM_INSTALL_DB", "MLDB")
    
    model_type = os.environ["MODEL_LANGUAGE"]
    with open("metadata.json") as f:
        metadata = json.load(f)
        
    column_expression = metadata["trainedModel"]["metadata"]["byomColumnExpression"]
    with open(f"{context.artifact_input_path}/model.{model_type.lower()}", "rb") as f:
        model_bytes = f.read()
    model = store_byom_tmp(get_context(), byom_temp_table, context.model_version, model_bytes)

    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]
    entity_key = context.dataset_info.entity_key    
    
    test_df = DataFrame.from_query(context.dataset_info.sql)
    
    if model_type in ["PMML"]:
        pmml = PMMLPredict(
            modeldata=model,
            newdata=test_df,
            accumulate=[entity_key,target_name])
        predictions_df = pmml.result
    else:
        raise ValueError(f"Model type {model_type} not supported.")

    # Dataframe is available as a view
    predictions_df._DataFrame__execute_node_and_set_table_name(predictions_df._nodeid, predictions_df._metaexpr)

    predictions_df = DataFrame.from_query(f"""
    SELECT 
        {entity_key},
        {target_name} as {target_name},
        {column_expression} AS prediction
    FROM {predictions_df._table_name}
    """)

    predictions_pdf = predictions_df.to_pandas()

    statistics = valib.Frequency(data=predictions_df, columns=target_name)
    eval_stats = ClassificationEvaluator(data=predictions_df, observation_column=target_name, prediction_column='prediction', num_labels=int(statistics.result.count(True).to_pandas().count_xval))
    eval_data = eval_stats.output_data.to_pandas().reset_index(drop=True)

    evaluation = {
        'Accuracy': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Accuracy')].MetricValue.item()),
        'Recall': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Recall')].MetricValue.item()),
        'Precision': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Precision')].MetricValue.item()),
        'f1-score': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-F1')].MetricValue.item())
    }

    with open(f"{context.artifact_output_path}/metrics.json", "w+") as f:
        json.dump(evaluation, f)

    # create confusion matrix plot
    cf = metrics.confusion_matrix(predictions_pdf[[target_name]], predictions_pdf[["prediction"]])
    cm = metrics.ConfusionMatrixDisplay(confusion_matrix=cf, display_labels=statistics.result.select('xval').to_pandas().xval.to_list())
    cm.plot()
    save_plot('Confusion Matrix', context=context)

    # calculate stats if training stats exist
    if os.path.exists(f"{context.artifact_input_path}/data_stats.json"):
        record_evaluation_stats(features_df=test_df,
                                predicted_df=predictions_df,
                                context=context)
    else:
        logging.debug("data_stats.json not found. Skipping compute statistics.")

    remove_context()

In [ ]:
# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the evaluation dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_Base_Features F 
JOIN (Select ID, label from Sonar_Base_Labels where sample_id in (2,4)) L
ON F.ID = L.ID
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_Base_Statistics_Metadata"
}
hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_t', 'Skewness_t', 'StandardDeviation_t', 'Maximum_t', 'Kurtosis_t',
       'Mean_t', 'ACF_1', 'ACF_2', 'ACF_3', 'ACF_4', 'ACF_5', 'ACF_6', 'ACF_7',
       'ACF_8', 'ACF_9', 'ACF_10', 'ACF_11', 'ACF_12', 'ACF_13', 'ACF_14',
       'ACF_15']


dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata)

ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   artifact_input_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1")

evaluate(context=ctx)

# view evaluation results
with open(f"{ctx.artifact_output_path}/metrics.json") as f:
    print(json.load(f))

## CWT

### Training

The training function takes the following shape

```python
def train(context: ModelContext, **kwargs):
    aoa_create_context()
    
    # your training code
    
    # save your model
    joblib.dump(model, f"{context.artifact_output_path}/model.joblib")
    
    record_training_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [94]:
from aoa import (
    record_training_stats,
    save_plot,
    aoa_create_context,
    ModelContext
)
from teradataml import *
import pandas as pd

def train(context: ModelContext, **kwargs):
    aoa_create_context()
    
    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]
    feature_names_str = ",".join(["'{}'".format(value) for value in feature_names])
    
    # read training dataset from Teradata and convert to pandas
    train_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Starting training...")

    # fit model to training data
    model_query = f'''
    CREATE TABLE Sonar_DF_CWT AS (
        SELECT * FROM TD_DecisionForest(
            ON ({context.dataset_info.sql}) as InputTable
        USING
            ResponseColumn('label')
            InputColumns({feature_names_str})
            ModelType('CLASSIFICATION')
            MaxDepth({context.hyperparams["MaxDepth"]})
            NumTrees({context.hyperparams["NumTrees"]})
            MinNodeSize({context.hyperparams["MinNodeSize"]})
            Mtry({context.hyperparams["Mtry"]})
        ) AS dt
    ) WITH DATA;'''

    try:
        pd.read_sql(model_query,get_context())
    except:
        pd.read_sql(f'DROP TABLE Sonar_DF_CWT;',get_context())
        pd.read_sql(model_query,get_context())

    print("Finished training")
    # export model artefacts
    
    print("Saved trained model")

    record_training_stats(train_df,
                          features=feature_names,
                          targets=[target_name],
                          categorical=[target_name],
                          context=context)

In [85]:
from aoa import ModelContext, DatasetInfo
from teradataml import configure

# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the training dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_CWT_Features F 
JOIN (Select ID, label from Sonar_CWT_Labels where sample_id in (1,3)) L
ON F.ID = L.ID
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_CWT_Statistics_Metadata"
}
hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_0','Maximum_0','Skewness_0','StandardDeviation_0','Kurtosis_0','Mean_0','Minimum_1','Maximum_1','Skewness_1',
 'StandardDeviation_1','Kurtosis_1','Mean_1','Minimum_2','Maximum_2','Skewness_2','StandardDeviation_2','Kurtosis_2','Mean_2','Minimum_3',
 'Maximum_3','Skewness_3','StandardDeviation_3','Kurtosis_3','Mean_3','Minimum_4','Maximum_4','Skewness_4','StandardDeviation_4','Kurtosis_4',
 'Mean_4','Minimum_5','Maximum_5','Skewness_5','StandardDeviation_5','Kurtosis_5','Mean_5','Minimum_6','Maximum_6','Skewness_6','StandardDeviation_6',
 'Kurtosis_6','Mean_6','Minimum_7','Maximum_7','Skewness_7','StandardDeviation_7','Kurtosis_7','Mean_7','Minimum_8','Maximum_8','Skewness_8',
 'StandardDeviation_8','Kurtosis_8','Mean_8','Minimum_9','Maximum_9','Skewness_9','StandardDeviation_9','Kurtosis_9','Mean_9','Minimum_10',
 'Maximum_10','Skewness_10','StandardDeviation_10','Kurtosis_10','Mean_10','Minimum_11','Maximum_11','Skewness_11','StandardDeviation_11',
 'Kurtosis_11','Mean_11','Minimum_12','Maximum_12','Skewness_12','StandardDeviation_12','Kurtosis_12','Mean_12','Minimum_13','Maximum_13',
 'Skewness_13','StandardDeviation_13','Kurtosis_13','Mean_13','Minimum_14','Maximum_14','Skewness_14','StandardDeviation_14','Kurtosis_14',
 'Mean_14','Minimum_15','Maximum_15','Skewness_15','StandardDeviation_15','Kurtosis_15','Mean_15','Minimum_16','Maximum_16','Skewness_16',
 'StandardDeviation_16','Kurtosis_16','Mean_16','Minimum_17','Maximum_17','Skewness_17','StandardDeviation_17','Kurtosis_17','Mean_17','Minimum_18',
 'Maximum_18','Skewness_18','StandardDeviation_18','Kurtosis_18','Mean_18','Minimum_19','Maximum_19','Skewness_19','StandardDeviation_19',
 'Kurtosis_19','Mean_19','Minimum_20','Maximum_20','Skewness_20','StandardDeviation_20','Kurtosis_20','Mean_20']
 
dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata)


ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1")

train(context=ctx)

Starting training...
Finished training
Saved trained model

### Evaluation

The evaluation function takes the following shape

```python
def evaluate(context: ModelContext, **kwargs):
    aoa_create_context()

    # read your model
    model = joblib.load(f"{context.artifact_input_path}/model.joblib")
    
    # your evaluation logic
    
    record_evaluation_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [86]:
from sklearn import metrics
from teradataml import *
from aoa import (
    record_evaluation_stats,
    save_plot,
    aoa_create_context,
    ModelContext
)

import json
import pandas as pd

def evaluate(context: ModelContext, **kwargs):
    aoa_create_context()
    #configure.val_install_location = os.environ.get("AOA_VAL_INSTALL_DB", "TRNG_XSP") 
     
    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]

    test_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Evaluating")

    query = f'''
        SELECT * FROM TD_DecisionForestPredict (
            ON ({context.dataset_info.sql}) AS InputTable
            ON Sonar_DF_CWT AS ModelTable DIMENSION
        USING
            IdColumn ('{context.dataset_info.entity_key}')
            Responses('0','1')
            Accumulate('{context.dataset_info.target_names[0]}')
            OutputProb('true')
        ) AS dt;'''
    
    predictions_df = DataFrame.from_query(query)
    
    print("Finished Evaluating")

    statistics = valib.Frequency(data=predictions_df, columns=target_name)
    eval_stats = ClassificationEvaluator(data=predictions_df, observation_column=target_name, prediction_column='prediction', num_labels=int(statistics.result.count(True).to_pandas().count_xval))
    eval_data = eval_stats.output_data.to_pandas().reset_index(drop=True)

    evaluation = {
        'Accuracy': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Accuracy')].MetricValue.item()),
        'Recall': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Recall')].MetricValue.item()),
        'Precision': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-Precision')].MetricValue.item()),
        'f1-score': '{:.2f}'.format(eval_data[eval_data.Metric.str.startswith('Macro-F1')].MetricValue.item())
    }

    with open(f"{context.artifact_output_path}/metrics.json", "w+") as f:
        json.dump(evaluation, f)
        
    # Confusion Matrix sklearn metrics
    predictions_pdf = predictions_df.to_pandas()
    cm = metrics.confusion_matrix(predictions_pdf[target_name],predictions_pdf["prediction"])
    cmd = metrics.ConfusionMatrixDisplay(cm,display_labels = ['notWhale','Whale'])
    cmd.plot()
    save_plot('Confusion Matrix', context=context)
    
    fpr, tpr, thresholds = metrics.roc_curve(predictions_pdf[target_name],predictions_pdf["prediction"] , pos_label=1)
    roc_AUC = metrics.auc(fpr,tpr)
    rcd = metrics.RocCurveDisplay(fpr = fpr, tpr = tpr,roc_auc = roc_AUC, estimator_name = 'TD_DecisionForest')
    
    rcd.plot()
    save_plot('ROC Curve', context=context)
    
    record_evaluation_stats(features_df=test_df,
                            predicted_df=predictions_df,
                            context=context)

In [87]:
# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the evaluation dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_CWT_Features F 
JOIN (Select ID, label from Sonar_CWT_Labels where sample_id in (2,4)) L
ON F.ID = L.ID
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_CWT_Statistics_Metadata"
}
hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_0','Maximum_0','Skewness_0','StandardDeviation_0','Kurtosis_0','Mean_0','Minimum_1','Maximum_1','Skewness_1',
 'StandardDeviation_1','Kurtosis_1','Mean_1','Minimum_2','Maximum_2','Skewness_2','StandardDeviation_2','Kurtosis_2','Mean_2','Minimum_3',
 'Maximum_3','Skewness_3','StandardDeviation_3','Kurtosis_3','Mean_3','Minimum_4','Maximum_4','Skewness_4','StandardDeviation_4','Kurtosis_4',
 'Mean_4','Minimum_5','Maximum_5','Skewness_5','StandardDeviation_5','Kurtosis_5','Mean_5','Minimum_6','Maximum_6','Skewness_6','StandardDeviation_6',
 'Kurtosis_6','Mean_6','Minimum_7','Maximum_7','Skewness_7','StandardDeviation_7','Kurtosis_7','Mean_7','Minimum_8','Maximum_8','Skewness_8',
 'StandardDeviation_8','Kurtosis_8','Mean_8','Minimum_9','Maximum_9','Skewness_9','StandardDeviation_9','Kurtosis_9','Mean_9','Minimum_10',
 'Maximum_10','Skewness_10','StandardDeviation_10','Kurtosis_10','Mean_10','Minimum_11','Maximum_11','Skewness_11','StandardDeviation_11',
 'Kurtosis_11','Mean_11','Minimum_12','Maximum_12','Skewness_12','StandardDeviation_12','Kurtosis_12','Mean_12','Minimum_13','Maximum_13',
 'Skewness_13','StandardDeviation_13','Kurtosis_13','Mean_13','Minimum_14','Maximum_14','Skewness_14','StandardDeviation_14','Kurtosis_14',
 'Mean_14','Minimum_15','Maximum_15','Skewness_15','StandardDeviation_15','Kurtosis_15','Mean_15','Minimum_16','Maximum_16','Skewness_16',
 'StandardDeviation_16','Kurtosis_16','Mean_16','Minimum_17','Maximum_17','Skewness_17','StandardDeviation_17','Kurtosis_17','Mean_17','Minimum_18',
 'Maximum_18','Skewness_18','StandardDeviation_18','Kurtosis_18','Mean_18','Minimum_19','Maximum_19','Skewness_19','StandardDeviation_19',
 'Kurtosis_19','Mean_19','Minimum_20','Maximum_20','Skewness_20','StandardDeviation_20','Kurtosis_20','Mean_20']



dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata)

ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   artifact_input_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1")

evaluate(context=ctx)

# view evaluation results
with open(f"{ctx.artifact_output_path}/metrics.json") as f:
    print(json.load(f))

Evaluating
Finished Evaluating

/var/folders/s4/bz6clqz1235_rx2pr6_pm44c0000gq/T/ipykernel_45097/3659115632.py:40: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eval_stats = ClassificationEvaluator(data=predictions_df, observation_column=target_name, prediction_column='prediction', num_labels=int(statistics.result.count(True).to_pandas().count_xval))

{'Accuracy': '0.81', 'Recall': '0.81', 'Precision': '0.81', 'f1-score': '0.81'}

### Scoring

The scoring function takes the following shape

```python
def score(context: ModelContext, **kwargs):
    aoa_create_context()

    # read your model
    model = joblib.load(f"{context.artifact_input_path}/model.joblib")
    
    # your evaluation logic
    
    record_scoring_stats(...)
```

You can execute this from the CLI or directly within the notebook as shown.

In [93]:
# %%writefile ../model_modules/scoring.py

from teradataml import *
from aoa import (
    record_scoring_stats,
    aoa_create_context,
    ModelContext
)

import pandas as pd
import json

def JSON(x):
    Dict = {"prob_0":x["prob_0"],"prob_1":x["prob_1"],"prediction":x["prediction"]}
    return json.dumps(Dict)

def score(context: ModelContext, **kwargs):

    aoa_create_context()

    feature_names = context.dataset_info.feature_names
    target_name = context.dataset_info.target_names[0]
    entity_key = context.dataset_info.entity_key

    features_df = DataFrame.from_query(context.dataset_info.sql)
    
    print("Scoring")
    
    predictions_df = DataFrame.from_query(
        f'''SELECT * FROM TD_DecisionForestPredict (
            ON ({context.dataset_info.sql}) AS InputTable
            ON Sonar_DF_CWT AS ModelTable DIMENSION
        USING
            IdColumn ('{context.dataset_info.entity_key}')
            Responses('0','1')
            OutputProb('true')
        ) AS dt;''')
    
    print("Finished Scoring")

    # store the predictions
    predictions_pdf = predictions_df.to_pandas(all_rows = True)
    # add job_id column so we know which execution this is from if appended to predictions table
    predictions_pdf["job_id"] = context.job_id
    predictions_pdf["json_report"] = predictions_pdf.apply(JSON,axis = 1)
    predictions_pdf.rename(columns={"prediction": target_name}, inplace=True) 
    predictions_pdf = predictions_pdf[["job_id", entity_key, target_name, "json_report"]]

    copy_to_sql(df=predictions_pdf,
                schema_name=context.dataset_info.predictions_database,
                table_name=context.dataset_info.predictions_table,
                index=False,
                if_exists="append")
    
    print("Saved predictions in Teradata")

    # calculate stats of this job
    predictions_df = DataFrame.from_query(f"""
        SELECT 
            * 
        FROM {context.dataset_info.get_predictions_metadata_fqtn()} 
            WHERE job_id = '{context.job_id}'
    """)

    record_scoring_stats(features_df=features_df, predicted_df=predictions_df, context=context)

In [89]:
from aoa import ModelContext, DatasetInfo
from teradataml import configure
# Define the ModelContext to test with. The ModelContext is created and managed automatically by ModelOps 
# when it executes your code via CLI / UI. However, for testing in the notebook, you can define as follows

# define the scoring dataset 
sql = """
SELECT 
    F.*, L.label
FROM Sonar_CWT_Features F 
JOIN (Select ID, label from Sonar_CWT_Labels) L
ON F.ID = L.ID
where F.ID MOD 5 = 0
"""

feature_metadata =  {
    "database": username,
    "table": "Sonar_CWT_Statistics_Metadata"
}

predictions = {
    "database": username,
    "table": "Sonar_CWT_Predictions"
}

hyperparams = {"MaxDepth": 12, "NumTrees": 36, "MinNodeSize": 1, "Mtry": 15}

entity_key = 'ID'
target_names = ['label']
feature_names = ['Minimum_0','Maximum_0','Skewness_0','StandardDeviation_0','Kurtosis_0','Mean_0','Minimum_1','Maximum_1','Skewness_1',
 'StandardDeviation_1','Kurtosis_1','Mean_1','Minimum_2','Maximum_2','Skewness_2','StandardDeviation_2','Kurtosis_2','Mean_2','Minimum_3',
 'Maximum_3','Skewness_3','StandardDeviation_3','Kurtosis_3','Mean_3','Minimum_4','Maximum_4','Skewness_4','StandardDeviation_4','Kurtosis_4',
 'Mean_4','Minimum_5','Maximum_5','Skewness_5','StandardDeviation_5','Kurtosis_5','Mean_5','Minimum_6','Maximum_6','Skewness_6','StandardDeviation_6',
 'Kurtosis_6','Mean_6','Minimum_7','Maximum_7','Skewness_7','StandardDeviation_7','Kurtosis_7','Mean_7','Minimum_8','Maximum_8','Skewness_8',
 'StandardDeviation_8','Kurtosis_8','Mean_8','Minimum_9','Maximum_9','Skewness_9','StandardDeviation_9','Kurtosis_9','Mean_9','Minimum_10',
 'Maximum_10','Skewness_10','StandardDeviation_10','Kurtosis_10','Mean_10','Minimum_11','Maximum_11','Skewness_11','StandardDeviation_11',
 'Kurtosis_11','Mean_11','Minimum_12','Maximum_12','Skewness_12','StandardDeviation_12','Kurtosis_12','Mean_12','Minimum_13','Maximum_13',
 'Skewness_13','StandardDeviation_13','Kurtosis_13','Mean_13','Minimum_14','Maximum_14','Skewness_14','StandardDeviation_14','Kurtosis_14',
 'Mean_14','Minimum_15','Maximum_15','Skewness_15','StandardDeviation_15','Kurtosis_15','Mean_15','Minimum_16','Maximum_16','Skewness_16',
 'StandardDeviation_16','Kurtosis_16','Mean_16','Minimum_17','Maximum_17','Skewness_17','StandardDeviation_17','Kurtosis_17','Mean_17','Minimum_18',
 'Maximum_18','Skewness_18','StandardDeviation_18','Kurtosis_18','Mean_18','Minimum_19','Maximum_19','Skewness_19','StandardDeviation_19',
 'Kurtosis_19','Mean_19','Minimum_20','Maximum_20','Skewness_20','StandardDeviation_20','Kurtosis_20','Mean_20']



import uuid
job_id=str(uuid.uuid4())

dataset_info = DatasetInfo(sql=sql,
                           entity_key=entity_key,
                           feature_names=feature_names,
                           target_names=target_names,
                           feature_metadata=feature_metadata,
                           predictions=predictions)

ctx = ModelContext(hyperparams=hyperparams,
                   dataset_info=dataset_info,
                   artifact_output_path="tmp",
                   artifact_input_path="tmp",
                   model_version="v1",
                   model_table="aoa_model_v1",
                   job_id=job_id)

score(context=ctx)

Scoring
Finished Scoring

/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1452: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TIMESTAMP(timezone=True) if pt.is_datetime64_ns_dtype(df.dtypes[key])
/Users/muhammadshaheer/anaconda3/envs/ModelOpsTMOENV/lib/python3.11/site-packages/teradataml/dataframe/copy_to.py:1454: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  else _get_sqlalchemy_mapping(str(df.dtypes[key]))

Saved predictions in Teradata

In [95]:
str(uuid.uuid4())

'1f714ada-045a-401b-a487-35718c09e186'

In [ ]:
25657b07-68f4-5cb8-926d-ea7af579dffd

In [ ]:
9c5c61cc-05ac-4c92-bf56-f24313910ff8